// src/Desktop/KeyCard.Desktop/Views/MainWindow.axaml.cs
using System;

using Avalonia.Controls;
using Avalonia.Platform;

namespace KeyCard.Desktop.Views
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();     // generated by Avalonia when namespace/class matches
            TrySetWindowIcon();        // bulletproof: programmatic icon as fallback
        }

        private void TrySetWindowIcon()
        {
            // Prefer Branding/KeyCard.ico; fall back to Assets/KeyCard.ico
            try
            {
                var uri = new Uri("avares://KeyCard.Desktop/Assets/Branding/KeyCard.ico");
                using var s = AssetLoader.Open(uri);
                Icon = new WindowIcon(s);
                return;
            }
            catch { /* continue */ }

            try
            {
                var uri2 = new Uri("avares://KeyCard.Desktop/Assets/KeyCard.ico");
                using var s2 = AssetLoader.Open(uri2);
                Icon = new WindowIcon(s2);
            }
            catch
            {
                // Swallow; app still runs with default icon.
            }
        }
    }
}
