services:
  api:
    build:
      context: ..
      dockerfile: build/Dockerfile.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Use service name 'postgres' inside the network
      POSTGRES_CONNECTION: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      REDIS_CONNECTION: "redis:6379"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ..
      dockerfile: build/Dockerfile.web
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Web needs to know how to call API from inside container:
      API_BASE_URL: "http://api:8080"
    ports:
      - "8081:8081"
    depends_on:
      - api

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
